from defs import *
import pyautogui as pg
import pyperclip

# codigo = str(input('Por favor digite o código da peça: '))
codigo = 'sp271'

#abrir o chrome
pg.hotkey('win', 'r')
digitar('chrome')
pg.press('enter')
time.sleep(1)
pg.press('tab')
pg.press('enter')
time.sleep(0.25)
digitar('peca.ai')
time.sleep(0.25)
pg.press('enter')
time.sleep(4)
clickar_imagem(r'imagens/busca_peca.ai.png')
pg.press('tab')
digitar(codigo)
time.sleep(0.25)
pg.press('enter')
time.sleep(1.5)
clickar_imagem(r'imagens/entrar_peca.ai.png')
time.sleep(0.5)
pg.press('f5')
time.sleep(3)
for c in range(0, 17):
    pg.press('tab')
pg.press('enter')
time.sleep(2)
pg.click(x=151, y=651)
pg.click(x=151, y=651)
pg.hotkey('ctrl', 'c')
pg.hotkey('ctrl', 'shift', 'alt', 'win', 'x')
time.sleep(4)
pg.press('tab')
pg.press('tab')
pg.write('Planilha de Base para Cotacao')
time.sleep(1)
pg.press('enter')
time.sleep(2)
escrever_celula('b2', codigo)
pg.click(x=56, y=181)
pg.write('c2')
pg.press('enter')
pg.hotkey('ctrl', 'v')
